---
# Ansible connection
ansible_host: "{{ application_server_two_private_ip }}"
deployed_site_name: "{{ application_server_two_private_ip }}"
server_hostname: "app2"
tally_ho_django_init_commands:
  - check --settings={{ tally_ho_django_app_settings_module }}
