---

# default values
deployment_environment: "production"
# Ansible
ansible_python_interpreter: "/usr/bin/env python3"

# Monitoring
set_hostname: false
server_monitoring_monit_scripts: ["monit", "system", "openssh-server"]
monit_opsgenie_api_key: "{{ server_monitoring_opsgenie_api_key }}"

install_collectd: true
collectd_scripts_initial:
  - "graphite"
  - "cpu"
  - "disk"
  - "load"
  - "memory"
collectd_graphite_server_ip: "{{ tallyho_monitoring_server_address }}"
collectd_graphite_server_port: 2003
collectd_graphite_server_protocol: "tcp"
collectd_server_type: "{{ deployment_environment }}"
collectd_server_owner: "{{ deployment_owner }}"