# UFW
ufw_slack_deployed_domain: "{{ ansible_host }}"
ufw_rules:
  - port: 22
    rule: "allow"
    from_ip: any
    comment: "Allow SSH"
  - port: 80
    rule: "allow"
    from_ip: any
    comment: "Allow HTTP traffic to NGINX"
  - port: 443
    rule: "allow"
    from_ip: any
    comment: "Allow HTTPS traffic to NGINX"
